# Inventory file for Kong Konnect Control Planes and Groups

all:
  children:
    konnect_control_planes:
      hosts:
        konnect-control-plane-1:
          name: konnect-control-plane-1
          controlPlaneID: 9524ec7d-36d9-465d-a8c5-83a3c9390458
          description: "Control Plane 1"
          auth_type: pki_client_certs
          certificates:
            # See: https://docs.konghq.com/konnect/gateway-manager/data-plane-nodes/secure-communications/#set-certificate-authentication-mode
            - name: "root-ca-1"
              cert: "Key Goes Here"
            - name: "root-ca-2"
              cert: "Key Goes Here"
